import { useEffect, useRef, useState } from 'react';
import { Icon } from '../shell/icons';

const lessons = [
  { file: 'first_steps.py', code: ['# Big ideas start with small steps.', '', 'def learn_together(people):', '    for person in people:', '        print(f"Hello, {person}!")', '', 'team = ["You", "Asha", "Alex"]', 'learn_together(team)'], output: ['Hello, You!', 'Hello, Asha!', 'Hello, Alex!'], note: 'A loop gives everyone a turn.', body: 'The for loop visits each name in your team. One shared idea, three little hellos.' },
  { file: 'fibonacci.py', code: ['# Every step builds on the last.', '', 'def fibonacci(n):', '    a, b = 0, 1', '    for _ in range(n):', '        print(a, end=" ")', '        a, b = b, a + b', '', 'fibonacci(8)'], output: ['0 1 1 2 3 5 8 13'], note: 'Two values. An endless pattern.', body: 'Each new number is the sum of the two before it. Try tracing a and b through a few iterations.' },
  { file: 'small_wins.py', code: ['# Consistency is a superpower.', '', 'minutes = [15, 20, 10, 25, 30]', 'total = sum(minutes)', '', 'print(f"{total} minutes of progress.")', 'print("See you tomorrow.")'], output: ['100 minutes of progress.', 'See you tomorrow.'], note: 'It all adds up.', body: 'sum() combines every value in a list. Small sessions can become something substantial.' },
];
function Code({ line }: { line: string }) {
  if (line.startsWith('#')) return <span className="code-comment">{line}</span>;
  return <>{line.split(/("[^"]*"|\b(?:def|for|in|print|range|sum)\b|\b\d+\b)/g).map((part, i) => <span key={i} className={part.startsWith('"') ? 'code-string' : /^(def|for|in)$/.test(part) ? 'code-keyword' : /^(print|range|sum)$/.test(part) ? 'code-function' : /^\d+$/.test(part) ? 'code-number' : ''}>{part}</span>)}</>;
}
export function StudioPreview({ onStart }: { onStart: () => void }) {
  const [selected, setSelected] = useState(0);
  const [ran, setRan] = useState(false);
  const [running, setRunning] = useState(false);
  const [tab, setTab] = useState<'learn' | 'people'>('learn');
  const timeout = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => () => { if (timeout.current) clearTimeout(timeout.current); }, []);
  const lesson = lessons[selected];
  function run() { setRunning(true); setRan(false); timeout.current = setTimeout(() => { setRunning(false); setRan(true); }, 650); }
  function select(index: number) { if (timeout.current) clearTimeout(timeout.current); setSelected(index); setRan(false); setRunning(false); }
  return <div className="preview-wrap" id="workspace-preview">
    <div className="preview-caption"><span><span className="live-dot"/> A SPACE TO THINK. TOGETHER.</span><span>INTERACTIVE PREVIEW <span className="caption-arrow">↙</span></span></div>
    <div className="studio-preview">
      <div className="preview-top"><div className="window-dots"><i/><i/><i/></div><span className="preview-breadcrumb">Workspace <span>/</span> <strong>the-learning-lab</strong><Icon name="chevron" size={12}/></span><span className="preview-shared"><Icon name="users" size={14}/> Shared space</span><div className="mini-avatars"><span>Y</span><span>A</span><span>AL</span></div></div>
      <div className="preview-main">
        <aside className="preview-files"><div className="preview-label">EXPLORER <Icon name="plus" size={13}/></div><div className="folder-label"><Icon name="chevron" size={12}/> learning-lab</div>{lessons.map((item, i) => <button key={item.file} onClick={() => select(i)} className={selected === i ? 'selected' : ''}><span className="file-symbol">⌘</span>{item.file}{selected === i && <span className="file-dot"/>}</button>)}<div className="explorer-foot"><Icon name="lock" size={13}/><span>Shared code.<br/>Your own discoveries.</span></div></aside>
        <div className="preview-editor"><div className="preview-editor-head"><span><span className="file-symbol">⌘</span>{lesson.file}<span className="unsaved-dot"/></span><button className="preview-run" onClick={run} disabled={running} aria-label="Run preview code"><span className={running ? 'tiny-spinner' : ''}>{running ? '' : '▷'}</span>{running ? 'Running' : 'Run code'}</button></div><div className="preview-code" key={lesson.file}>{lesson.code.map((line, i) => <div className="code-line" key={i}><span className="line-number">{i + 1}</span><code><Code line={line}/>{i === 4 && <span className="collab-caret"><span>Asha</span></span>}</code></div>)}<div className="code-line"><span className="line-number">{lesson.code.length + 1}</span><code><span className="local-caret"/></code></div></div><div className="preview-terminal"><div className="terminal-head"><span><span className="terminal-prompt">⌁</span> TERMINAL <span className="terminal-private"><Icon name="lock" size={10}/> Only you</span></span><span className={ran ? 'terminal-success' : ''}>{ran ? '✓ Completed' : 'Python 3'}</span></div><div className="terminal-content" aria-live="polite">{running ? <span className="code-comment">Running example…</span> : ran ? <><span className="terminal-command">$ python {lesson.file}</span>{lesson.output.map(line => <div key={line}>{line}</div>)}</> : <><span className="terminal-command">$ python {lesson.file}<span className="terminal-block"/></span><span className="terminal-hint">A small experiment is a good place to start. Hit Run code.</span></>}</div></div></div>
        <aside className="preview-learn"><div className="preview-learn-tabs"><button className={tab === 'learn' ? 'active' : ''} onClick={() => setTab('learn')}><Icon name="checklist" size={14}/> Learn</button><button className={tab === 'people' ? 'active' : ''} onClick={() => setTab('people')}><Icon name="users" size={14}/> People <span>3</span></button></div>{tab === 'learn' ? <div className="learning-content" key={selected}><span className="lesson-tag">THE LITTLE THINGS / 0{selected + 1}</span><div className="learning-glyph" aria-hidden="true"><span>{selected === 1 ? '∞' : selected === 2 ? '∑' : '↳'}</span><i/><i/></div><h3>{lesson.note}</h3><p>{lesson.body}</p><div className="lesson-takeaway"><Icon name="check" size={14}/>{ran ? 'You just took another step.' : 'Understanding > memorizing'}</div><span className="preview-note">Illustrative lesson · try the examples</span></div> : <div className="preview-people"><span className="lesson-tag">EXAMPLE COLLABORATORS</span>{[['Y', 'You', 'Exploring'], ['A', 'Asha', 'Writing a little Python'], ['AL', 'Alex', 'Learning alongside you']].map(([initial, name, status]) => <div className="preview-person" key={name}><span className="person-avatar">{initial}</span><div><strong>{name}</strong><small>{status}</small></div><span className="live-dot"/></div>)}<p>In your room, see who is here and follow their edits as they happen.</p><button className="text-link" onClick={onStart}>Bring your people <Icon name="arrow" size={14}/></button></div>}</aside>
      </div><div className="preview-status"><span><span className="live-dot"/> Example workspace <span className="status-divider">/</span> Changes happen together</span><span>UTF-8 <span className="status-divider">/</span> Python <span className="status-divider">/</span> Ln {lesson.code.length + 1}, Col 1</span></div>
    </div>
  </div>;
}
